### ISSUE TITLE
RPC, P2P и magic

### ISSUE THREAD

**Issue by cibermax** [kzcashteam/kzcash#1]
Приветствую ребята напишите порты RPC P2P и еще magic требуется для поднятия своего пула

**Comment by kzcashteam** [comment]
@cibermax 
P2P: 8277
RPC: 8276
Magic header: bd1b44ba

Не забудьте учесть награду для мастернод при сборе блока. :)

**Comment by cibermax** [comment]
Не подскажете как это поправить в NOMP ?????
